### ISSUE TITLE
HomeAssistantType warning

### ISSUE THREAD

**Issue by dmatik** [litinoveweedle/hass-template-climate#18]
### The problem

After updating HA to 2024.5.X new Warning in the logs.
Actually not really sure if it was not there before.

HomeAssistantType was used from climate_template, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'climate_template' custom integration.

### What version of Template Climate has the issue?

0.7.0

### What version of Home Assistant are you running?

2024.5.1

### What type of installation are you running?

Home Assistant Container

**Comment by litinoveweedle** [comment]
Yep, can confirm it, I will try to fix this. Thanks for report

**Comment by litinoveweedle** [comment]
Fixed by https://github.com/litinoveweedle/hass-template-climate/pull/21
