### ISSUE TITLE
[FR]: Template key for is heating? 

### ISSUE THREAD

**Issue by s1mpleman** [litinoveweedle/hass-template-climate#26]
### Is your feature request related to a problem? Please describe.

Hello! Thank you again for this integration it's been working great. 

Maybe I am missing something, and I'm not entirely sure what this would be called in HA so excuse my ignorance here. 

Currently I don't see a way to indicate whether the heater is actively heating. As you can see in the below screenshot. The bottom wiser climate entity lights up when it's actively heating. This one did when the temperature set point was over the room temperature until I override the set_temperature command. That wasn't really ideal anyway. 
![Screenshot_2024-11-29-15-38-34-22_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/476054b0-0951-493e-8e1d-69f55c5b42d0)

Would this be possible at all? 

If it's too much work then don't worry as it's just a nicety feature more than anything. 

### Describe the solution you'd like

I'd like a way to specify by a template whether the heater is actively heating or not to trigger the UI display on the climate cards. 

### Describe alternatives you've considered

It's not a dire need would just be nice. There may be another way already but I couldnt tell with the available documentation. 

### Additional context

This is because I currently use this template over another climate entity and do all the controls for that climate through this templated climate.

**Comment by litinoveweedle** [comment]
Hello, thank you for the very structured feature request. So in short you would like to have the template to indicate current [HVAC action](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action), correct? If so I should be able to implement it easily.

**Comment by s1mpleman** [comment]
> Hello, thank you for the very structured feature request. So in short you would like to have the template to indicate current [HVAC action](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action), correct? If so I should be able to implement it easily.

Yes that would be perfect! Thank you so much. I didn't realise that's what HA used so good to know as well.

**Comment by s1mpleman** [comment]
> Hello, thank you for the very structured feature request. So in short you would like to have the template to indicate current [HVAC action](https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action), correct? If so I should be able to implement it easily.

Just found this hvac_action_template template key. Seems it's already implemented? I'll test it out and close this if so :)

**Comment by s1mpleman** [comment]
Yep that works fine, closing :)

**Comment by litinoveweedle** [comment]
You see, that happens when developer doesn't remember what he already implemented. ;-) I am glad that you found it anyway. :-)
